services:
  shop:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shop
    environment:
      - DB_URL=jdbc:mariadb://db:3306/shop
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - PORT=12345
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=12345678
      - MINIO_BUCKET_NAME=shop-bucket
      - MINIO_ENDPOINT=http://minio:9000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  php-gateway:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: shop-php-gateway
    environment:
      - JAVA_HOST=shop
      - JAVA_PORT=12345
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      shop:
        condition: service_started

  db:
    container_name: shop-db
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: shop
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  redis:
    image: redis
    container_name: shop-redis
    restart: always

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 12345678
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  db_data:
  minio_data: